@startuml 

actor Main
actor Input

actor JPallina
actor JSabbia
actor JScatola

actor datiCondivisi

actor ThScatola
actor ThInput

Main-->Main: faiPartireITh()


Main-->ThScatola:start()
Main-->ThInput:start()



@enduml